### ISSUE TITLE
make new release because of base64 dep?

### ISSUE THREAD

**Issue by Dushistov** [EstebanBorai/http-auth-basic#8]
`cargo tree -d` for my project show:

```
base64 v0.12.3
└── http-auth-basic v0.3.1
    └── couchbase-lite v0.6.0 (/home/evgeniy/bigdisk1/projects/rust-infra/couchbase-lite-rust/couchbase-lite)

base64 v0.13.0
└── tungstenite v0.17.2
    └── tokio-tungstenite v0.17.1
        └── couchbase-lite v0.6.0 (/home/evgeniy/bigdisk1/projects/rust-infra/couchbase-lite-rust/couchbase-lite)
```

and as I see base64 dep was updated in master, so why not release new version to fix this?

**Comment by EstebanBorai** [comment]
@Dushistov of course! I have to setup a CI workflow to automate these updates. Thanks for notifying!

**Comment by EstebanBorai** [comment]
Here it is @Dushistov https://crates.io/crates/http-auth-basic/0.3.3/dependencies.
Version `0.3.3` should be good to go!

I will be working on how to release this automatically to avoid these issues. Thanks for collaborating!
Feel free to reopen if you encounter any issues.
